spring:
  flyway:
    out-of-order: true
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:mysql://localhost:3306/chess
    username: root
    password: BDgaming3BDgaming3BDgaming3
    driver-class-name: com.mysql.cj.jdbc.Driver

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger